### PR TITLE
Mochawesome Report Generator 3.0 compatibility

### LINKED ISSUE #8: Add compatibility for Mochawesome Report Generator 3.x
To address #7 

Need to add Mochawesome Report Generator as a peer dependency

### PR DESCRIPTION
**Pull request by sfbwalder**
Added `reporter-v3` (and associated test configurations) which is compatible with 3.0 of the Mochawesome Report Generator.  Also made a few updates to fix some lint errors.

I wasn't sure how you would want to implement the 3.0 reporter, so I made it a separate reporter, allowing you to see the differences with the current reporter.  I can make whatever changes you want if you can decide how you want to implement it.

I published this version internally, and it is working successfully in a few of our pipelines.

Fixes #8.

### CODE REVIEW

**Comment by sfbwalder** [comment]
The failing tests run fine locally, not sure why they are failing in the build.  Thoughts?

**Comment by sfbwalder** [comment]
Rebased to d84b672afc0ed21c5fccc087b30f52bde9b26c23.  Test failing with the same path issue as master.

Any thoughts on how you want to proceed with making it compatible with 3.0 #8?

**Comment by snoblenet** [comment]
i fixed that test here: https://github.com/fijijavis/wdio-mochawesome-reporter/blob/master/test/specs/tests.js#L256

**Comment by wynnfarm** [comment]
rebased again to keep this pull request up to date.  Any thoughts on what you want adjusted so this can be merged?

**Comment by fijijavis** [comment]
@wynnfarm @sfbwalder @snoblenet 
Thanks for the contribution.  I like the idea of having separate reporters for backwards compatibility.  

A few thoughts...

* I think we need an ```index.js``` file at the root of the project that exports v2 and v3 reporters.  That should make it a little cleaner for consumption.

* Looks like a couple enhancements are missing:
  * Ability to specify if you want relative or absolute path for screenshtos
  * Selenium Session ID automatically included as context.

* ```README.md``` needs to be updated with info on the 2 versions available.

**Comment by jeckerman** [comment]
Whatever came of this?

**Comment by fijijavis** [comment]
@jeckerman AFAICT no action has been taken on my comments from 02/24.

**Comment by sfbwalder** [comment]
Sorry, we haven't had time to get back to this.  We have it working internally, but would still like to see 3.0 support rolled into the public package.  We are not sure when we will get back to this.

**Comment by x-yifeixu** [comment]
Any movements on this? I would love to have this feature

**Comment by fijijavis** [comment]
I did some major refactoring over the weekend and released a v2.0.0 which has support for MARGE 3.x

**Pull request closed without merging**
